language: java
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
