/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package snailmail

import snailmail.client.ClientSession
import snailmail.core.UserCredentials
import snailmail.core.api.AuthSuccessful
import snailmail.server.Server
import kotlin.test.*

class AppTest {
    @Test fun testMyGovnokod() {
        val server = Server()
        val alice = ClientSession(server)
        val bob = ClientSession(server)

        val aliceToken = (server.register(UserCredentials("alice", "secret1")) as AuthSuccessful).token
        val bobToken = (server.register(UserCredentials("bob", "secret2")) as AuthSuccessful).token

        val aliceUser = server.searchByUsername(aliceToken, "alice")!!
        val bobUser = server.searchByUsername(bobToken, "bob")!!

        assertEquals(server.getAvailableChats(aliceToken).getChats(), listOf())
        assertEquals(server.getAvailableChats(bobToken).getChats(), listOf())

        val aliceChat = server.getPersonalChatWith(aliceToken, bobUser.id)
        val bobChat = server.getPersonalChatWith(bobToken, aliceUser.id)

        assertEquals(aliceChat.id, bobChat.id)
    }
}
