/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package snailmail

import snailmail.client.Client
import snailmail.core.TextMessage
import snailmail.core.User
import snailmail.core.UserCredentials
import snailmail.core.api.AuthSuccessful
import snailmail.server.Server
import javax.xml.soap.Text
import kotlin.test.*

class ClientServerTest {
    @Test
    fun `client-server simple integrity test`() {
        val server = Server()
        val alice = Client(server)
        val bob = Client(server)

        assert(alice.register(UserCredentials("alice", "alice123")))
        assert(bob.register(UserCredentials("bob", "bob345")))

        assertEquals(alice.findAvailableChats(), emptyList())
        assertEquals(bob.findAvailableChats(), emptyList())

        assertEquals(alice.getPersonalChatHistory("alice"), emptyList())

        alice.sendMessage("bob", "Hi, bob!")
        assertEquals(bob.getPersonalChatHistory("alice").size, 1)
        val msg = bob.getPersonalChatHistory("alice").first()
        assertEquals((msg as TextMessage).content, "Hi, bob!")
    }
}
